services:
  fastapi:
    build: .
    ports:
      - "8080:8080" # Map container port 8080 to host port 8080
    environment: # Specify environment variables here
      DATABASE_HOSTNAME: "mongodb" # MongoDB connection string
      DATABASE_PORT: 27017
      DATABASE_NAME: ideaNestdb
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_MINUTES: 10080
    depends_on:
      - mongodb
    volumes:
      - .:/app
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: